.TH "SearchAlgorithmExtensions.cs" 3 "Version 1.0" "Mazes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchAlgorithmExtensions.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\&.SearchAlgorithmExtensions\fP"
.br
.RI "An extension class for \fBGraph\fP that implements searching algorithms as well as their complementary paths\&. "
.ti -1c
.RI "class \fBGraph\&.DistanceHeuristicAlgorithms\fP"
.br
.ti -1c
.RI "class \fBGraph\&.GreedyAlgorithmExtensions\fP"
.br
.RI "An extension class for \fBWeightedGraph\fP that implements greedy algorithms as well as their complementary paths\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGraph\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mazes from the source code\&.
