.TH "Graph.DistanceHeuristicAlgorithms" 3 "Version 1.0" "Mazes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph.DistanceHeuristicAlgorithms
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBEuclidianDistance< T >\fP (T x1, T y1, T x2, T y2)"
.br
.ti -1c
.RI "static double \fBManhattanDistance< T >\fP (T x1, T y1, T x2, T y2)"
.br
.ti -1c
.RI "static double \fBDiagonalDistance< T >\fP (T x1, T y1, T x2, T y2)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static double Graph\&.DistanceHeuristicAlgorithms\&.DiagonalDistance< T > (T x1, T y1, T x2, T y2)\fR [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIINumber<T>\fP
.SS "static double Graph\&.DistanceHeuristicAlgorithms\&.EuclidianDistance< T > (T x1, T y1, T x2, T y2)\fR [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIINumber<T>\fP
.SS "static double Graph\&.DistanceHeuristicAlgorithms\&.ManhattanDistance< T > (T x1, T y1, T x2, T y2)\fR [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIINumber<T>\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Mazes from the source code\&.
