.TH "Graph" 3 "Version 1.0" "Mazes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectionalGraph\fP"
.br
.RI "a directional graph implementation based on the \fBGraph\fP Class\&. "
.ti -1c
.RI "class \fBDistanceHeuristicAlgorithms\fP"
.br
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "a \fBGraph\fP Implementation for non null types\&. "
.ti -1c
.RI "class \fBGraphsMain\fP"
.br
.RI "a wrapper class for our main function to test our graphs and algorithms\&. "
.ti -1c
.RI "class \fBGreedyAlgorithmExtensions\fP"
.br
.RI "An extension class for \fBWeightedGraph\fP that implements greedy algorithms as well as their complementary paths\&. "
.ti -1c
.RI "class \fBNonNegativeWeightedGraph\fP"
.br
.RI "a weighted graph implementation based on the \fBGraph\fP Class forcing non-negative weights\&. "
.ti -1c
.RI "class \fBSearchAlgorithmExtensions\fP"
.br
.RI "An extension class for \fBGraph\fP that implements searching algorithms as well as their complementary paths\&. "
.ti -1c
.RI "class \fBWeightedDirectionalGraph\fP"
.br
.RI "a weighted directional graph implementation based on the \fBGraph\fP Class\&. "
.ti -1c
.RI "class \fBWeightedGraph\fP"
.br
.RI "a weighted graph implementation based on the \fBGraph\fP Class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mazes from the source code\&.
