.TH "Mazes" 3 "Version 1.0" "Mazes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mazes
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCoordinate2D\fP"
.br
.RI "A Coordinate Struct for representing 2D Coordinates\&. "
.ti -1c
.RI "class \fBCoordinateGraph\fP"
.br
.RI "a graph implementation based on the \fBGraph\fP Class using the coordinate struct\&. "
.ti -1c
.RI "class \fBNonNegativeWeightedCoordinateGraph\fP"
.br
.RI "a graph implementation based on the NonNegativeWeightedGraph Class using the coordinate struct\&. "
.ti -1c
.RI "class \fBWeightedCoordinateGraph\fP"
.br
.RI "a graph implementation based on the WeightedGraph Class using the coordinate struct\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Mazes from the source code\&.
